# Generated by Django 5.2.11 on 2026-03-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hoodie', 'Hoodie'), ('cap', 'Cap'), ('pants', 'Pants'), ('tshirt', 'T-Shirt'), ('shorts', 'Shorts'), ('hoodie_pants', 'Hoodie Pants'), ('accessories', 'Accessories'), ('gymfit', 'Gymfit'), ('sando', 'Sando')], max_length=100),
        ),
    ]
