# Generated by Django 5.2.11 on 2026-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookbookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='lookbook/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('collection', models.CharField(choices=[('season1', 'Season 1'), ('season2', 'Season 2'), ('latest', 'Latest Drop')], default='latest', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
